name = "FEMSolids"
uuid = "bac82deb-c58f-4e3c-8f6d-c1bcdafeba40"
version = "0.3"
authors = ["kimauth <auth@chalmers.se> and contributors"]

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
Ferrite = "1"
Tensors = "1.16.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
